version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory:         "/"
    schedule:
      interval: "weekly"
      day:      "friday"
      time:     "06:00"
    assignees:
      - "burgholzer"

  - package-ecosystem: "github-actions"
    directory:         "/"
    schedule:
      interval: "weekly"
      day:      "friday"
      time:     "06:00"
    assignees:
      - "burgholzer"

  - package-ecosystem: "pip"
    directory:         "/"
    schedule:
      interval: "weekly"
      day:      "friday"
      time:     "06:00"
    assignees:
      - "burgholzer"
